jp_configuration:
    resource: "@JPConfigurationBundle/Resources/config/routing.yml"
    prefix:   /configuration

jp_profession:
    resource: "@JPProfilBundle/Resources/config/routing/profession.yml"
    prefix:   /p

jp_formation:
    resource: "@JPProfilBundle/Resources/config/routing/formation.yml"
    prefix:   /f

jp_organe:
    resource: "@JPProfilBundle/Resources/config/routing/organe.yml"
    prefix:   /o

jp_club:
    resource: "@JPProfilBundle/Resources/config/routing/club.yml"
    prefix:   /c

jp_main:
    resource: "@JPMainBundle/Resources/config/routing.yml"
    prefix:   /

jp_cotisation:
    resource: "@JPCotisationBundle/Resources/config/routing/cotisation.yml"
    prefix:   /cotisation

jp_reunion:
    resource: "@JPReunionBundle/Resources/config/routing.yml"
    prefix:   /reunion

jp_profil:
    resource: "@JPProfilBundle/Resources/config/routing.yml"
    prefix:   /profil

jp_user:
    resource: "@JPUserBundle/Resources/config/routing.yml"
    prefix:   /user

jp_cotisation_paiement:
    path:     /cotisation/paiement
    defaults: { _controller: JPCotisationBundle:Default:indexPaiement }

jp_cotisation_paiement_add:
    path:     /cotisation/{id}/paiement
    defaults: { _controller: JPCotisationBundle:Default:addPaiement }

jp_cotisation_payer:
    path:     /cotisation/{id}/payement
    defaults: { _controller: JPCotisationBundle:Default:payement }

jp_cotisation_paye:
    path:     /cotisation/{id}/{profil}/payement
    defaults: { _controller: JPCotisationBundle:Default:payementshow }

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"


fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile


fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register


fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting


fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile