<?php

namespace JP\ProfilBundle\Repository;

/**
 * ConjointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConjointRepository extends \Doctrine\ORM\EntityRepository
{
}
