<?php

namespace JP\ProfilBundle\Repository;

/**
 * MoyenComRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoyenComRepository extends \Doctrine\ORM\EntityRepository
{
}
