<?php

namespace JP\ProfilBundle\Repository;

/**
 * NumeroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NumeroRepository extends \Doctrine\ORM\EntityRepository
{
}
