<?php

namespace JP\ProfilBundle\Repository;


/**
 * 0rganeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrganeRepository extends \Doctrine\ORM\EntityRepository
{
}
