<?php

namespace JP\ProfilBundle\Repository;

/**
 * ProfilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilRepository extends \Doctrine\ORM\EntityRepository
{

	public function FindMemberProfil($idA,$idB)
		{

		  $qb = $this->createQueryBuilder('a');

		  $qb

		    ->Where('a.profiltype = :idA')
		    	 ->setParameter('idA', $idA)
		    ->orWhere('a.profiltype = :idB ')		   
		  		  ->setParameter('idB', $idB)

		  ;


		  return $qb

		    ->getQuery()

		    ->getResult()

		  ;

		}


public function CountMemberProfil($idA,$idB)
		{

		  $qb = $this->createQueryBuilder('a');

		  $qb

		    ->Where('a.profiltype = :idA')
		    	 ->setParameter('idA', $idA)
		    ->orWhere('a.profiltype = :idB ')		   
		  		  ->setParameter('idB', $idB)

		  ;


		  return $qb

		    ->getQuery()

		    ->getSingleScalarResult()

		  ;

		}


public function findProfilByCode($idA,$idB)
		{

		  $qb = $this->createQueryBuilder('b')
		  	;
		  $qb
		    ->Where('b.id = :idA')
		    	 ->setParameter('idA', $idA)
		    ->andWhere('b.code = :idB ')		   
		  		  ->setParameter('idB', $idB)
		  	;
		  return $qb
				    ->getQuery()
				    ->getResult()
		  	;

		}


		
}
