profil_member_club_index:
    path:     /
    defaults: { _controller: "JPProfilBundle:Club:index" }
    methods:  GET

profil_member_club_show:
    path:     /{id}/show
    defaults: { _controller: "JPProfilBundle:Club:show" }
    methods:  GET

profil_member_club_new:
    path:     /new
    defaults: { _controller: "JPProfilBundle:Club:new" }
    methods:  [GET, POST]

profil_member_club_edit:
    path:     /{id}/edit
    defaults: { _controller: "JPProfilBundle:Club:edit" }
    methods:  [GET, POST]

profil_member_club_delete:
    path:     /{id}/delete
    defaults: { _controller: "JPProfilBundle:Club:delete" }
    methods:  DELETE
