<?php

namespace JP\CotisationBundle\Repository;

/**
 * CotisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CotisationRepository extends \Doctrine\ORM\EntityRepository
{
}
