<?php

namespace JP\ReunionBundle\Repository;

/**
 * ReunionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReunionRepository extends \Doctrine\ORM\EntityRepository
{




	public function findReunion()
		{

		  $qb = $this->createQueryBuilder('r');

		  $qb
		  	->orderBy('r.datereunion', 'DESC')
		     ;


		  return $qb

		    ->getQuery()

		    ->getResult()

		  ;

		}
}
